Feature/create_mongo_db-GDEV-115
ghga-de/sandbox-request pull request #3
Opened 2021-08-12 10:04 UTC by alamgirmani

2021-08-12 13:53 UTC, deepakunni3 requested changes
Looks good @alamgirmani ! Just a few comments above.

2021-08-12 13:53 UTC, deepakunni3 commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
Can we remove IntelliJ specific configurations? Looks like `.idea` folder was included in the repo.

2021-08-12 13:53 UTC, deepakunni3 commented on README.md
> +# Sandbox Sandbox Service
Typo?

2021-08-12 13:53 UTC, deepakunni3 commented on sandbox_request/__init__.py
> +"""
Perhaps it would be neater to have the module docstring after the license text.

2021-08-12 14:54 UTC, alamgirmani commented on sandbox_request/__init__.py
> +"""
moved the docstrings below the licence text

2021-08-12 14:54 UTC, alamgirmani commented on README.md
> +# Sandbox Sandbox Service
fixed the typo

2021-08-12 15:29 UTC, alamgirmani commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
Removed the Intellij files and folders

2021-08-13 07:48 UTC, deepakunni3 commented on sandbox_request/__init__.py
> +"""
I was suggesting the change for all python files, not just `__init__` 😅

2021-08-13 07:49 UTC, deepakunni3 approved these changes

2021-08-13 08:05 UTC, KerstenBreuer approved these changes
Great. If we can integrate the suggestions from #4, then this can be merged

2021-08-13 08:46 UTC, merged

2021-08-13 08:51 UTC, ac-jorellanaf commented on .devcontainer/docker-compose.yml
> +        - 5672:5672
Dont think these lines do anything.