feature/autogenerate_mongo_db_ids-GDEV-160
ghga-de/sandbox-request pull request #5
Opened 2021-08-16 16:09 UTC by alamgirmani

2021-08-17 13:49 UTC, ac-jorellanaf approved these changes

2021-08-17 14:51 UTC, deepakunni3 requested changes
@alamgirmani Looks good. Just a comment above regarding the ID formatting.

2021-08-17 14:51 UTC, deepakunni3 commented on sandbox_request/dao/request.py
> +    return "REQ:" + str(document["value"] + 1)
I would recommend padding the string with zeroes to resemble our ID formatting.
```py
return f"REQ:{document['value']:07}"
```

2021-08-17 16:17 UTC, KerstenBreuer requested changes
Looks good.

2021-08-17 16:17 UTC, KerstenBreuer commented on examples/requests.json
> +      "request_id": "REQ:0000001",
Why have you renamed the "id" to "request_id"? I think it's a common standard to name the id of an collection object as "id" and any references to foreign collections "{collection_name}_id".

No matter, what we decide on, I think, we should be consistent across the request and metadata service.

2021-08-17 16:17 UTC, KerstenBreuer commented on sandbox_request/dao/request.py
> +async def get_next_request_id(counter, collection_name):
Could we move this function to the top, as this is a dependency of `add_request`?

2021-08-18 06:13 UTC, alamgirmani commented on sandbox_request/dao/request.py
> +async def get_next_request_id(counter, collection_name):
Not sure if the positioning of the methods matters, is this a standard convention?

2021-08-18 06:14 UTC, alamgirmani commented on examples/requests.json
> +      "request_id": "REQ:0000001",
It was originally named "id" and we can revert back to "id". We will still have a mongo generated "_id". I will make this change.

2021-08-18 06:17 UTC, alamgirmani commented on sandbox_request/dao/request.py
> +    return "REQ:" + str(document["value"] + 1)
Thank you, I will reformat it as recommended

2021-08-18 06:34 UTC, alamgirmani commented on sandbox_request/dao/request.py
> +    return "REQ:" + str(document["value"] + 1)
pushed the changes

2021-08-18 06:34 UTC, alamgirmani commented on examples/requests.json
> +      "request_id": "REQ:0000001",
pushed the changes

2021-08-18 12:20 UTC, KerstenBreuer approved these changes

2021-08-18 12:24 UTC, merged